MODEL:
  GENERATE_DISTILL: True
  META_ARCHITECTURE: "GeneralizedRCNN"
  # WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  WEIGHT: "/gruntdata0/xinting/project/LVIS/maskxrcnn_for_base/ckps/ckp-top270_freeze2_resnet101_2/model_0060000_for_distill.pth"
  # WEIGHT: "/mnt/data-disk2/xinting/project/maskrcnn/ckp-coco/e2e_mask_rcnn_R_50_FPN_1x_trimmed.pth"
  QRY_BALANCE: False
#   QRY_INDICE_CLS: "/mnt/data-disk2/xinting/project/dataset/LVIS/lvis_trainval_1230/lvis_step1_2/lvis_classes_qry_step1_rand.json"
  NUM_DISTILL_CLASSES: 270
  BACKBONE:
    CONV_BODY: "R-101-FPN"
    FREEZE_CONV_BODY_AT: 4
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    DETECTIONS_PER_IMG: 300
    USE_FPN: True
    SCORE_THRESH: 0.00
    BATCH_SIZE_PER_IMAGE: 256
    POSITIVE_FRACTION: 0.5
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
#     PREDICTOR: "FPNPredictor"
#     FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"

    FEATURE_EXTRACTOR: "FPN2MLPCosineFeatureExtractor"
    PREDICTOR: "FPNCosinePredictor"

    NUM_CLASSES: 271 #copy 81 classes, the 1st one --background
  ROI_MASK_HEAD:
    USE_BBOX2MASK: True
    USE_MLPMASK: True
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
  CLS_AGNOSTIC_BBOX_REG: False
  FEW_SHOT:
    ScaleCls: 10
DATASETS:
  # TRAIN: ("coco_2014_train", "coco_2014_valminusminival")
  # TEST: ("coco_2014_minival",)
  # TRAIN: ("lvis_v0.5_minival",)
  # TEST: ("lvis_v0.5_minival",)
  TRAIN: ("lvis_v0.5_train_step1_320",)
  TEST: ("lvis_v0.5_train_step1_320",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0001
  STEPS: (50000, 70000)
  MAX_ITER: 100000
  IMS_PER_BATCH: 1
  TEST_PERIOD: 3000  #per 2500 step do validation
  CHECKPOINT_PERIOD: 3000
TEST:
  IMS_PER_BATCH: 1
OUTPUT_DIR: "./distill_step1_320"
TENSORBOARD_EXPERIMENT: "./logs-step1_freeze4/logs-step1_freeze4_balanced_accu"